language: node_js

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - chmod 700 bash
  - ./bash

  - echo "Starting build docker container..."
  - docker-compose up -d --build

script:
  - echo "finish"
